export const VerifyCodeDefaultProps = {
  txtSend: '发送验证码',
  txtSendAgain: '重发验证码',
  txtCountDown: '秒后重试',
  countDown: 60,
  isInitialActive: true,
  initActive: false,
  label: '验证码',
  controlled: false,
  type: 'text',
  password: false,
  placeholder: '请输入验证码',
  maxLength: 140,
  confirmType: 'done',
  confirmHold: false,
  selectionStart: -1,
  selectionEnd: -1,
  randomNumber: false,
  layer: 'horizontal',
  clear: true,
  autoFocus: false,
  disabled: false,
};
