export var DateRangePickerDefaultProps = {
    visible: null,
    defaultVisible: null,
    animationType: 'transform',
    format: 'YYYY/MM/DD',
    min: null,
    max: null,
    value: null,
    defaultValue: null,
    title: '',
    okText: '确定',
    cancelText: '取消',
    placeholder: '请选择',
    precision: 'day',
    splitCharacter: '-',
    startPlaceholder: '未选择',
    endPlaceholder: '未选择',
    maskClosable: true,
    popClassName: '',
    popStyle: '',
    disabled: false,
    onFormatLabel: null,
    onFormat: null,
};
