export var DateRangePickerDefaultProps = {
    okText: '确定',
    cancelText: '取消',
    maskClosable: true,
    placeholder: '请选择',
    format: 'YYYY/MM/DD',
    splitCharacter: '-',
    startPlaceholder: '未选择',
    endPlaceholder: '未选择',
    precision: 'day',
};
export var DateRangePickerFunctionalProps = {
    animationType: 'transform',
    format: 'YYYY/MM/DD',
    min: null,
    max: null,
    value: null,
    defaultValue: null,
    title: '',
    okText: '确定',
    cancelText: '取消',
    placeholder: '请选择',
    precision: 'day',
    splitCharacter: '-',
    startPlaceholder: '未选择',
    endPlaceholder: '未选择',
    maskClosable: true,
    popClassName: '',
    popStyle: '',
    disabled: false,
    onFormatLabel: null,
};
