export var TypographyDefaultProps = {
    text: '',
    iconPosition: 'right',
    icon: '',
    className: '',
    activeClassName: '',
    style: '',
    disabled: false,
    selectable: false,
    fontWeight: 'normal',
    lineThrough: false,
    underline: false,
    ellipsisRow: null,
    onTap: null,
    catchTap: null,
    onDisabledTap: null,
};
