"use strict";(self.webpackChunkantd_mini=self.webpackChunkantd_mini||[]).push([[9183],{56269:function(o,n,e){e.r(n),e.d(n,{demos:function(){return d}});var t=e(67294),a=e(16382),d={"src-auto-resize-demo-autoresize":{component:t.memo(t.lazy(function(){return e.e(2433).then(e.bind(e,18463))})),asset:{type:"BLOCK",id:"src-auto-resize-demo-autoresize",refAtomIds:[],dependencies:{},entry:"index.ts"},context:{},renderOpts:void 0}}},59514:function(o,n,e){e.r(n),e.d(n,{texts:function(){return a}});var t=e(16382);const a=[{value:"When multi-language adaptation of existing components is required, this component can be used in the original layout to complete the adaptation of different lengths of text in the component;",paraId:0,tocIndex:0},{value:"In ",paraId:1,tocIndex:1},{value:"index.json",paraId:1,tocIndex:1},{value:" Introducing Components in",paraId:1,tocIndex:1},{value:`"usingComponents": {
#if ALIPAY
  "ant-auto-resize": "antd-mini/es/AutoResize/index"
#endif
#if WECHAT
  "ant-auto-resize": "antd-mini/AutoResize/index"
#endif
}
`,paraId:2,tocIndex:1},{value:"Property",paraId:3,tocIndex:3},{value:"Description",paraId:3,tocIndex:3},{value:"Type",paraId:3,tocIndex:3},{value:"Default Value",paraId:3,tocIndex:3},{value:"text",paraId:3,tocIndex:3},{value:"Text to be passed in, used to calculate the width",paraId:3,tocIndex:3},{value:"string",paraId:3,tocIndex:3},{value:"-",paraId:3,tocIndex:3},{value:"minFontSize",paraId:3,tocIndex:3},{value:"The minimum font size limit can be set according to the business.",paraId:3,tocIndex:3},{value:"number",paraId:3,tocIndex:3},{value:"30",paraId:3,tocIndex:3},{value:"maxFontSize",paraId:3,tocIndex:3},{value:"The original design font size of this area, which cannot exceed this font size at most.",paraId:3,tocIndex:3},{value:"number",paraId:3,tocIndex:3},{value:"36",paraId:3,tocIndex:3},{value:"wrap",paraId:3,tocIndex:3},{value:"Whether to support line feed",paraId:3,tocIndex:3},{value:"boolean",paraId:3,tocIndex:3},{value:"false",paraId:3,tocIndex:3},{value:"ratio",paraId:3,tocIndex:3},{value:"Copy width ratio, calculated ",paraId:3,tocIndex:3},{value:"maxFontSize / ratio * Copy length",paraId:3,tocIndex:3},{value:", there are scenes where the English characters are long but the container width is enough to display, but the font is reduced, which can be increased at this time.",paraId:3,tocIndex:3}]}}]);
