// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/node_modules/dumi/theme-default/slots/ColorSwitch/index.js';
