// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/houmi/Desktop/work-project/ant-design-mini/node_modules/dumi/theme-default/slots/SourceCodeEditor/index.js';
