// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jiajia/Ali/Task/ant-design-mini/node_modules/dumi/theme-default/slots/Tabs/index.js';
