export var sliderDefaultProps = {
    value: null,
    defaultValue: null,
    disabled: false,
    max: 100,
    min: 0,
    range: false,
    showNumber: false,
    step: 1,
    showTicks: false,
    showTooltip: false,
    activeLineStyle: '',
    activeDotStyle: '',
    activeLineClassName: '',
    activeDotClassName: '',
};
