export var InputDefaultProps = {};
export var InputFunctionalProps = {
    type: null,
    value: null,
    defaultValue: null,
    placeholder: null,
    placeholderClassName: null,
    placeholderStyle: null,
    allowClear: null,
    enableNative: null,
    confirmType: null,
    confirmHold: null,
    controlled: null,
    alwaysSystem: null,
    selectionStart: null,
    selectionEnd: null,
    cursor: null,
    maxLength: -1,
    alwaysEmbed: false,
    cursorSpacing: 0,
    cursorColor: null,
    adjustPosition: true,
    holdKeyboard: false,
    inputClassName: null,
    inputStyle: null,
    password: null,
    prefix: null,
    disabled: null,
    focusClassName: null,
    suffix: null,
    focus: null,
    name: null,
    focusStyle: null,
    randomNumber: null,
};
