// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/customize-theme.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/customize-theme.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/using-uni-app.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/using-uni-app.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/migration-v1.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/migration-v1.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/migration-v2.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/migration-v2.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/using-wechat.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/using-wechat.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/cooperation.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/cooperation.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/quick-start.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/quick-start.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/contribute.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/contribute.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/faq.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/faq.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/resources.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/jiajia/Ali/Task/ant-design-mini/docs/resources.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/ActionSheet/index.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/ActionSheet/index.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Avatar/index.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Avatar/index.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Badge/index.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Badge/index.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Button/index.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Button/index.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Calendar/index.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Calendar/index.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Checkbox/index.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Checkbox/index.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Checklist/index.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Checklist/index.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Collapse/index.md?type=frontmatter';
import { demoIndex as dmi17 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Collapse/index.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/ConfigProvider/index.md?type=frontmatter';
import { demoIndex as dmi18 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/ConfigProvider/index.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Container/index.md?type=frontmatter';
import { demoIndex as dmi19 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Container/index.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/DatePicker/index.md?type=frontmatter';
import { demoIndex as dmi20 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/DatePicker/index.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Divider/index.md?type=frontmatter';
import { demoIndex as dmi21 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Divider/index.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Empty/index.md?type=frontmatter';
import { demoIndex as dmi22 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Empty/index.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Form/index.md?type=frontmatter';
import { demoIndex as dmi23 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Form/index.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Grid/index.md?type=frontmatter';
import { demoIndex as dmi24 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Grid/index.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/GuideTour/index.md?type=frontmatter';
import { demoIndex as dmi25 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/GuideTour/index.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Icon/index.md?type=frontmatter';
import { demoIndex as dmi26 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Icon/index.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/ImageUpload/index.md?type=frontmatter';
import { demoIndex as dmi27 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/ImageUpload/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/IndexBar/index.md?type=frontmatter';
import { demoIndex as dmi28 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/IndexBar/index.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Input/index.md?type=frontmatter';
import { demoIndex as dmi29 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Input/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/List/index.md?type=frontmatter';
import { demoIndex as dmi30 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/List/index.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Loading/index.md?type=frontmatter';
import { demoIndex as dmi31 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Loading/index.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Modal/index.md?type=frontmatter';
import { demoIndex as dmi32 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Modal/index.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/NoticeBar/index.md?type=frontmatter';
import { demoIndex as dmi33 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/NoticeBar/index.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/NumberKeyboard/index.md?type=frontmatter';
import { demoIndex as dmi34 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/NumberKeyboard/index.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/PageContainer/index.md?type=frontmatter';
import { demoIndex as dmi35 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/PageContainer/index.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Picker/index.md?type=frontmatter';
import { demoIndex as dmi36 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Picker/index.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Popover/index.md?type=frontmatter';
import { demoIndex as dmi37 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Popover/index.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Popup/index.md?type=frontmatter';
import { demoIndex as dmi38 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Popup/index.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Progress/index.md?type=frontmatter';
import { demoIndex as dmi39 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Progress/index.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Radio/index.md?type=frontmatter';
import { demoIndex as dmi40 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Radio/index.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/RareWordsKeyboard/index.md?type=frontmatter';
import { demoIndex as dmi41 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/RareWordsKeyboard/index.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Rate/index.md?type=frontmatter';
import { demoIndex as dmi42 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Rate/index.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Result/index.md?type=frontmatter';
import { demoIndex as dmi43 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Result/index.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Selector/index.md?type=frontmatter';
import { demoIndex as dmi44 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Selector/index.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Skeleton/index.md?type=frontmatter';
import { demoIndex as dmi45 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Skeleton/index.md?type=demo-index';
import { frontmatter as fm46, toc as t46 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Slider/index.md?type=frontmatter';
import { demoIndex as dmi46 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Slider/index.md?type=demo-index';
import { frontmatter as fm47, toc as t47 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Stepper/index.md?type=frontmatter';
import { demoIndex as dmi47 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Stepper/index.md?type=demo-index';
import { frontmatter as fm48, toc as t48 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Steps/index.md?type=frontmatter';
import { demoIndex as dmi48 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Steps/index.md?type=demo-index';
import { frontmatter as fm49, toc as t49 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/SwipeAction/index.md?type=frontmatter';
import { demoIndex as dmi49 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/SwipeAction/index.md?type=demo-index';
import { frontmatter as fm50, toc as t50 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Switch/index.md?type=frontmatter';
import { demoIndex as dmi50 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Switch/index.md?type=demo-index';
import { frontmatter as fm51, toc as t51 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/TabBar/index.md?type=frontmatter';
import { demoIndex as dmi51 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/TabBar/index.md?type=demo-index';
import { frontmatter as fm52, toc as t52 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Tabs/index.md?type=frontmatter';
import { demoIndex as dmi52 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Tabs/index.md?type=demo-index';
import { frontmatter as fm53, toc as t53 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Tag/index.md?type=frontmatter';
import { demoIndex as dmi53 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Tag/index.md?type=demo-index';
import { frontmatter as fm54, toc as t54 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Toast/index.md?type=frontmatter';
import { demoIndex as dmi54 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Toast/index.md?type=demo-index';
import { frontmatter as fm55, toc as t55 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Typography/index.md?type=frontmatter';
import { demoIndex as dmi55 } from '/Users/jiajia/Ali/Task/ant-design-mini/src/Typography/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide/customize-theme': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/customize-theme.md?type=text'),
  },
  'docs/guide/using-uni-app': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/using-uni-app.md?type=text'),
  },
  'docs/guide/migration-v1': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/migration-v1.md?type=text'),
  },
  'docs/guide/migration-v2': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/migration-v2.md?type=text'),
  },
  'docs/guide/using-wechat': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/using-wechat.md?type=text'),
  },
  'docs/guide/cooperation': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/cooperation.md?type=text'),
  },
  'docs/guide/quick-start': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/quick-start.md?type=text'),
  },
  'docs/guide/contribute': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/contribute.md?type=text'),
  },
  'docs/guide/faq': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/guide/faq.md?type=text'),
  },
  'docs/resources': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiajia/Ali/Task/ant-design-mini/docs/resources.md?type=text'),
  },
  'components/ActionSheet/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__ActionSheet" */'/Users/jiajia/Ali/Task/ant-design-mini/src/ActionSheet/index.md?type=text'),
  },
  'components/Avatar/index': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__Avatar" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Avatar/index.md?type=text'),
  },
  'components/Badge/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__Badge" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Badge/index.md?type=text'),
  },
  'components/Button/index': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__Button" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Button/index.md?type=text'),
  },
  'components/Calendar/index': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__Calendar" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Calendar/index.md?type=text'),
  },
  'components/Checkbox/index': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__Checkbox" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Checkbox/index.md?type=text'),
  },
  'components/Checklist/index': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__Checklist" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Checklist/index.md?type=text'),
  },
  'components/Collapse/index': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__Collapse" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Collapse/index.md?type=text'),
  },
  'components/ConfigProvider/index': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__ConfigProvider" */'/Users/jiajia/Ali/Task/ant-design-mini/src/ConfigProvider/index.md?type=text'),
  },
  'components/Container/index': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__Container" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Container/index.md?type=text'),
  },
  'components/DatePicker/index': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__DatePicker" */'/Users/jiajia/Ali/Task/ant-design-mini/src/DatePicker/index.md?type=text'),
  },
  'components/Divider/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__Divider" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Divider/index.md?type=text'),
  },
  'components/Empty/index': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__Empty" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Empty/index.md?type=text'),
  },
  'components/Form/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__Form" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Form/index.md?type=text'),
  },
  'components/Grid/index': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__Grid" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Grid/index.md?type=text'),
  },
  'components/GuideTour/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__GuideTour" */'/Users/jiajia/Ali/Task/ant-design-mini/src/GuideTour/index.md?type=text'),
  },
  'components/Icon/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__Icon" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Icon/index.md?type=text'),
  },
  'components/ImageUpload/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__ImageUpload" */'/Users/jiajia/Ali/Task/ant-design-mini/src/ImageUpload/index.md?type=text'),
  },
  'components/IndexBar/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__IndexBar" */'/Users/jiajia/Ali/Task/ant-design-mini/src/IndexBar/index.md?type=text'),
  },
  'components/Input/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__Input" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Input/index.md?type=text'),
  },
  'components/List/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__List" */'/Users/jiajia/Ali/Task/ant-design-mini/src/List/index.md?type=text'),
  },
  'components/Loading/index': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__Loading" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Loading/index.md?type=text'),
  },
  'components/Modal/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__Modal" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Modal/index.md?type=text'),
  },
  'components/NoticeBar/index': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__NoticeBar" */'/Users/jiajia/Ali/Task/ant-design-mini/src/NoticeBar/index.md?type=text'),
  },
  'components/NumberKeyboard/index': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__NumberKeyboard" */'/Users/jiajia/Ali/Task/ant-design-mini/src/NumberKeyboard/index.md?type=text'),
  },
  'components/PageContainer/index': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__PageContainer" */'/Users/jiajia/Ali/Task/ant-design-mini/src/PageContainer/index.md?type=text'),
  },
  'components/Picker/index': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__Picker" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Picker/index.md?type=text'),
  },
  'components/Popover/index': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__Popover" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Popover/index.md?type=text'),
  },
  'components/Popup/index': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__Popup" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Popup/index.md?type=text'),
  },
  'components/Progress/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__Progress" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Progress/index.md?type=text'),
  },
  'components/Radio/index': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__Radio" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Radio/index.md?type=text'),
  },
  'components/RareWordsKeyboard/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__RareWordsKeyboard" */'/Users/jiajia/Ali/Task/ant-design-mini/src/RareWordsKeyboard/index.md?type=text'),
  },
  'components/Rate/index': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__Rate" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Rate/index.md?type=text'),
  },
  'components/Result/index': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__Result" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Result/index.md?type=text'),
  },
  'components/Selector/index': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__Selector" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Selector/index.md?type=text'),
  },
  'components/Skeleton/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__Skeleton" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Skeleton/index.md?type=text'),
  },
  'components/Slider/index': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__Slider" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Slider/index.md?type=text'),
  },
  'components/Stepper/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__Stepper" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Stepper/index.md?type=text'),
  },
  'components/Steps/index': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__Steps" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Steps/index.md?type=text'),
  },
  'components/SwipeAction/index': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__SwipeAction" */'/Users/jiajia/Ali/Task/ant-design-mini/src/SwipeAction/index.md?type=text'),
  },
  'components/Switch/index': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__Switch" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Switch/index.md?type=text'),
  },
  'components/TabBar/index': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__TabBar" */'/Users/jiajia/Ali/Task/ant-design-mini/src/TabBar/index.md?type=text'),
  },
  'components/Tabs/index': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__Tabs" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Tabs/index.md?type=text'),
  },
  'components/Tag/index': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__Tag" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Tag/index.md?type=text'),
  },
  'components/Toast/index': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__Toast" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Toast/index.md?type=text'),
  },
  'components/Typography/index': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__Typography" */'/Users/jiajia/Ali/Task/ant-design-mini/src/Typography/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
