// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/customize-theme.en.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/customize-theme.en.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-uni-app.en.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-uni-app.en.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/customize-theme.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/customize-theme.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v1.en.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v1.en.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v2.en.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v2.en.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-wechat.en.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-wechat.en.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/cooperation.en.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/cooperation.en.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/quick-start.en.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/quick-start.en.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/contribute.en.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/contribute.en.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-uni-app.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-uni-app.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v1.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v1.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v2.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v2.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-wechat.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-wechat.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/cooperation.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/cooperation.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/quick-start.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/quick-start.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/contribute.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/contribute.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/faq.en.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/faq.en.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/resources.en.md?type=frontmatter';
import { demoIndex as dmi17 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/resources.en.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/faq.md?type=frontmatter';
import { demoIndex as dmi18 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/faq.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/resources.md?type=frontmatter';
import { demoIndex as dmi19 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/resources.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ActionSheet/index.en.md?type=frontmatter';
import { demoIndex as dmi20 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ActionSheet/index.en.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ActionSheet/index.md?type=frontmatter';
import { demoIndex as dmi21 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ActionSheet/index.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Avatar/index.en.md?type=frontmatter';
import { demoIndex as dmi22 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Avatar/index.en.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Avatar/index.md?type=frontmatter';
import { demoIndex as dmi23 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Avatar/index.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Badge/index.en.md?type=frontmatter';
import { demoIndex as dmi24 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Badge/index.en.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Badge/index.md?type=frontmatter';
import { demoIndex as dmi25 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Badge/index.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Button/index.en.md?type=frontmatter';
import { demoIndex as dmi26 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Button/index.en.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Button/index.md?type=frontmatter';
import { demoIndex as dmi27 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Button/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Calendar/index.en.md?type=frontmatter';
import { demoIndex as dmi28 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Calendar/index.en.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Calendar/index.md?type=frontmatter';
import { demoIndex as dmi29 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Calendar/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checkbox/index.en.md?type=frontmatter';
import { demoIndex as dmi30 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checkbox/index.en.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checkbox/index.md?type=frontmatter';
import { demoIndex as dmi31 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checkbox/index.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checklist/index.en.md?type=frontmatter';
import { demoIndex as dmi32 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checklist/index.en.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checklist/index.md?type=frontmatter';
import { demoIndex as dmi33 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checklist/index.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Collapse/index.en.md?type=frontmatter';
import { demoIndex as dmi34 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Collapse/index.en.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Collapse/index.md?type=frontmatter';
import { demoIndex as dmi35 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Collapse/index.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Container/index.en.md?type=frontmatter';
import { demoIndex as dmi36 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Container/index.en.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Container/index.md?type=frontmatter';
import { demoIndex as dmi37 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Container/index.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/DatePicker/index.en.md?type=frontmatter';
import { demoIndex as dmi38 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/DatePicker/index.en.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/DatePicker/index.md?type=frontmatter';
import { demoIndex as dmi39 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/DatePicker/index.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Divider/index.en.md?type=frontmatter';
import { demoIndex as dmi40 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Divider/index.en.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Divider/index.md?type=frontmatter';
import { demoIndex as dmi41 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Divider/index.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Empty/index.en.md?type=frontmatter';
import { demoIndex as dmi42 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Empty/index.en.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Empty/index.md?type=frontmatter';
import { demoIndex as dmi43 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Empty/index.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Form/index.en.md?type=frontmatter';
import { demoIndex as dmi44 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Form/index.en.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Form/index.md?type=frontmatter';
import { demoIndex as dmi45 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Form/index.md?type=demo-index';
import { frontmatter as fm46, toc as t46 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Grid/index.en.md?type=frontmatter';
import { demoIndex as dmi46 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Grid/index.en.md?type=demo-index';
import { frontmatter as fm47, toc as t47 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Grid/index.md?type=frontmatter';
import { demoIndex as dmi47 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Grid/index.md?type=demo-index';
import { frontmatter as fm48, toc as t48 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/GuideTour/index.en.md?type=frontmatter';
import { demoIndex as dmi48 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/GuideTour/index.en.md?type=demo-index';
import { frontmatter as fm49, toc as t49 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/GuideTour/index.md?type=frontmatter';
import { demoIndex as dmi49 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/GuideTour/index.md?type=demo-index';
import { frontmatter as fm50, toc as t50 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Icon/index.en.md?type=frontmatter';
import { demoIndex as dmi50 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Icon/index.en.md?type=demo-index';
import { frontmatter as fm51, toc as t51 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Icon/index.md?type=frontmatter';
import { demoIndex as dmi51 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Icon/index.md?type=demo-index';
import { frontmatter as fm52, toc as t52 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ImageUpload/index.en.md?type=frontmatter';
import { demoIndex as dmi52 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ImageUpload/index.en.md?type=demo-index';
import { frontmatter as fm53, toc as t53 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ImageUpload/index.md?type=frontmatter';
import { demoIndex as dmi53 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ImageUpload/index.md?type=demo-index';
import { frontmatter as fm54, toc as t54 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/IndexBar/index.en.md?type=frontmatter';
import { demoIndex as dmi54 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/IndexBar/index.en.md?type=demo-index';
import { frontmatter as fm55, toc as t55 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/IndexBar/index.md?type=frontmatter';
import { demoIndex as dmi55 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/IndexBar/index.md?type=demo-index';
import { frontmatter as fm56, toc as t56 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Input/index.en.md?type=frontmatter';
import { demoIndex as dmi56 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Input/index.en.md?type=demo-index';
import { frontmatter as fm57, toc as t57 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Input/index.md?type=frontmatter';
import { demoIndex as dmi57 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Input/index.md?type=demo-index';
import { frontmatter as fm58, toc as t58 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/List/index.en.md?type=frontmatter';
import { demoIndex as dmi58 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/List/index.en.md?type=demo-index';
import { frontmatter as fm59, toc as t59 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/List/index.md?type=frontmatter';
import { demoIndex as dmi59 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/List/index.md?type=demo-index';
import { frontmatter as fm60, toc as t60 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Loading/index.en.md?type=frontmatter';
import { demoIndex as dmi60 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Loading/index.en.md?type=demo-index';
import { frontmatter as fm61, toc as t61 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Loading/index.md?type=frontmatter';
import { demoIndex as dmi61 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Loading/index.md?type=demo-index';
import { frontmatter as fm62, toc as t62 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Modal/index.en.md?type=frontmatter';
import { demoIndex as dmi62 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Modal/index.en.md?type=demo-index';
import { frontmatter as fm63, toc as t63 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Modal/index.md?type=frontmatter';
import { demoIndex as dmi63 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Modal/index.md?type=demo-index';
import { frontmatter as fm64, toc as t64 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NoticeBar/index.en.md?type=frontmatter';
import { demoIndex as dmi64 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NoticeBar/index.en.md?type=demo-index';
import { frontmatter as fm65, toc as t65 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NoticeBar/index.md?type=frontmatter';
import { demoIndex as dmi65 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NoticeBar/index.md?type=demo-index';
import { frontmatter as fm66, toc as t66 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NumberKeyboard/index.en.md?type=frontmatter';
import { demoIndex as dmi66 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NumberKeyboard/index.en.md?type=demo-index';
import { frontmatter as fm67, toc as t67 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NumberKeyboard/index.md?type=frontmatter';
import { demoIndex as dmi67 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NumberKeyboard/index.md?type=demo-index';
import { frontmatter as fm68, toc as t68 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/PageContainer/index.en.md?type=frontmatter';
import { demoIndex as dmi68 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/PageContainer/index.en.md?type=demo-index';
import { frontmatter as fm69, toc as t69 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/PageContainer/index.md?type=frontmatter';
import { demoIndex as dmi69 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/PageContainer/index.md?type=demo-index';
import { frontmatter as fm70, toc as t70 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Picker/index.en.md?type=frontmatter';
import { demoIndex as dmi70 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Picker/index.en.md?type=demo-index';
import { frontmatter as fm71, toc as t71 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Picker/index.md?type=frontmatter';
import { demoIndex as dmi71 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Picker/index.md?type=demo-index';
import { frontmatter as fm72, toc as t72 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popover/index.en.md?type=frontmatter';
import { demoIndex as dmi72 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popover/index.en.md?type=demo-index';
import { frontmatter as fm73, toc as t73 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popover/index.md?type=frontmatter';
import { demoIndex as dmi73 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popover/index.md?type=demo-index';
import { frontmatter as fm74, toc as t74 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popup/index.en.md?type=frontmatter';
import { demoIndex as dmi74 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popup/index.en.md?type=demo-index';
import { frontmatter as fm75, toc as t75 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popup/index.md?type=frontmatter';
import { demoIndex as dmi75 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popup/index.md?type=demo-index';
import { frontmatter as fm76, toc as t76 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Progress/index.en.md?type=frontmatter';
import { demoIndex as dmi76 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Progress/index.en.md?type=demo-index';
import { frontmatter as fm77, toc as t77 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Progress/index.md?type=frontmatter';
import { demoIndex as dmi77 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Progress/index.md?type=demo-index';
import { frontmatter as fm78, toc as t78 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Radio/index.en.md?type=frontmatter';
import { demoIndex as dmi78 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Radio/index.en.md?type=demo-index';
import { frontmatter as fm79, toc as t79 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Radio/index.md?type=frontmatter';
import { demoIndex as dmi79 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Radio/index.md?type=demo-index';
import { frontmatter as fm80, toc as t80 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/RareWordsKeyboard/index.en.md?type=frontmatter';
import { demoIndex as dmi80 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/RareWordsKeyboard/index.en.md?type=demo-index';
import { frontmatter as fm81, toc as t81 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/RareWordsKeyboard/index.md?type=frontmatter';
import { demoIndex as dmi81 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/RareWordsKeyboard/index.md?type=demo-index';
import { frontmatter as fm82, toc as t82 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Rate/index.en.md?type=frontmatter';
import { demoIndex as dmi82 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Rate/index.en.md?type=demo-index';
import { frontmatter as fm83, toc as t83 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Rate/index.md?type=frontmatter';
import { demoIndex as dmi83 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Rate/index.md?type=demo-index';
import { frontmatter as fm84, toc as t84 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Result/index.en.md?type=frontmatter';
import { demoIndex as dmi84 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Result/index.en.md?type=demo-index';
import { frontmatter as fm85, toc as t85 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Result/index.md?type=frontmatter';
import { demoIndex as dmi85 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Result/index.md?type=demo-index';
import { frontmatter as fm86, toc as t86 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Selector/index.en.md?type=frontmatter';
import { demoIndex as dmi86 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Selector/index.en.md?type=demo-index';
import { frontmatter as fm87, toc as t87 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Selector/index.md?type=frontmatter';
import { demoIndex as dmi87 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Selector/index.md?type=demo-index';
import { frontmatter as fm88, toc as t88 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Skeleton/index.en.md?type=frontmatter';
import { demoIndex as dmi88 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Skeleton/index.en.md?type=demo-index';
import { frontmatter as fm89, toc as t89 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Skeleton/index.md?type=frontmatter';
import { demoIndex as dmi89 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Skeleton/index.md?type=demo-index';
import { frontmatter as fm90, toc as t90 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Slider/index.en.md?type=frontmatter';
import { demoIndex as dmi90 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Slider/index.en.md?type=demo-index';
import { frontmatter as fm91, toc as t91 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Slider/index.md?type=frontmatter';
import { demoIndex as dmi91 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Slider/index.md?type=demo-index';
import { frontmatter as fm92, toc as t92 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Stepper/index.en.md?type=frontmatter';
import { demoIndex as dmi92 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Stepper/index.en.md?type=demo-index';
import { frontmatter as fm93, toc as t93 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Stepper/index.md?type=frontmatter';
import { demoIndex as dmi93 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Stepper/index.md?type=demo-index';
import { frontmatter as fm94, toc as t94 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Steps/index.en.md?type=frontmatter';
import { demoIndex as dmi94 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Steps/index.en.md?type=demo-index';
import { frontmatter as fm95, toc as t95 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Steps/index.md?type=frontmatter';
import { demoIndex as dmi95 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Steps/index.md?type=demo-index';
import { frontmatter as fm96, toc as t96 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/SwipeAction/index.en.md?type=frontmatter';
import { demoIndex as dmi96 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/SwipeAction/index.en.md?type=demo-index';
import { frontmatter as fm97, toc as t97 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/SwipeAction/index.md?type=frontmatter';
import { demoIndex as dmi97 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/SwipeAction/index.md?type=demo-index';
import { frontmatter as fm98, toc as t98 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Switch/index.en.md?type=frontmatter';
import { demoIndex as dmi98 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Switch/index.en.md?type=demo-index';
import { frontmatter as fm99, toc as t99 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Switch/index.md?type=frontmatter';
import { demoIndex as dmi99 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Switch/index.md?type=demo-index';
import { frontmatter as fm100, toc as t100 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/TabBar/index.en.md?type=frontmatter';
import { demoIndex as dmi100 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/TabBar/index.en.md?type=demo-index';
import { frontmatter as fm101, toc as t101 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/TabBar/index.md?type=frontmatter';
import { demoIndex as dmi101 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/TabBar/index.md?type=demo-index';
import { frontmatter as fm102, toc as t102 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tabs/index.en.md?type=frontmatter';
import { demoIndex as dmi102 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tabs/index.en.md?type=demo-index';
import { frontmatter as fm103, toc as t103 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tabs/index.md?type=frontmatter';
import { demoIndex as dmi103 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tabs/index.md?type=demo-index';
import { frontmatter as fm104, toc as t104 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tag/index.en.md?type=frontmatter';
import { demoIndex as dmi104 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tag/index.en.md?type=demo-index';
import { frontmatter as fm105, toc as t105 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tag/index.md?type=frontmatter';
import { demoIndex as dmi105 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tag/index.md?type=demo-index';
import { frontmatter as fm106, toc as t106 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Toast/index.en.md?type=frontmatter';
import { demoIndex as dmi106 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Toast/index.en.md?type=demo-index';
import { frontmatter as fm107, toc as t107 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Toast/index.md?type=frontmatter';
import { demoIndex as dmi107 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Toast/index.md?type=demo-index';
import { frontmatter as fm108, toc as t108 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Typography/index.en.md?type=frontmatter';
import { demoIndex as dmi108 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Typography/index.en.md?type=demo-index';
import { frontmatter as fm109, toc as t109 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Typography/index.md?type=frontmatter';
import { demoIndex as dmi109 } from '/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Typography/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide/customize-theme.en': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/customize-theme.en.md?type=text'),
  },
  'docs/guide/using-uni-app.en': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-uni-app.en.md?type=text'),
  },
  'docs/guide/customize-theme': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/customize-theme.md?type=text'),
  },
  'docs/guide/migration-v1.en': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v1.en.md?type=text'),
  },
  'docs/guide/migration-v2.en': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v2.en.md?type=text'),
  },
  'docs/guide/using-wechat.en': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-wechat.en.md?type=text'),
  },
  'docs/guide/cooperation.en': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/cooperation.en.md?type=text'),
  },
  'docs/guide/quick-start.en': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/quick-start.en.md?type=text'),
  },
  'docs/guide/contribute.en': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/contribute.en.md?type=text'),
  },
  'docs/guide/using-uni-app': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-uni-app.md?type=text'),
  },
  'docs/guide/migration-v1': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v1.md?type=text'),
  },
  'docs/guide/migration-v2': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/migration-v2.md?type=text'),
  },
  'docs/guide/using-wechat': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/using-wechat.md?type=text'),
  },
  'docs/guide/cooperation': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/cooperation.md?type=text'),
  },
  'docs/guide/quick-start': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/quick-start.md?type=text'),
  },
  'docs/guide/contribute': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/contribute.md?type=text'),
  },
  'docs/guide/faq.en': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/faq.en.md?type=text'),
  },
  'docs/resources.en': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/resources.en.md?type=text'),
  },
  'docs/guide/faq': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/guide/faq.md?type=text'),
  },
  'docs/resources': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/docs/resources.md?type=text'),
  },
  'components/ActionSheet/index.en': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__ActionSheet__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ActionSheet/index.en.md?type=text'),
  },
  'components/ActionSheet/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__ActionSheet" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ActionSheet/index.md?type=text'),
  },
  'components/Avatar/index.en': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__Avatar__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Avatar/index.en.md?type=text'),
  },
  'components/Avatar/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__Avatar" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Avatar/index.md?type=text'),
  },
  'components/Badge/index.en': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__Badge__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Badge/index.en.md?type=text'),
  },
  'components/Badge/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__Badge" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Badge/index.md?type=text'),
  },
  'components/Button/index.en': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__Button__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Button/index.en.md?type=text'),
  },
  'components/Button/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__Button" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Button/index.md?type=text'),
  },
  'components/Calendar/index.en': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__Calendar__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Calendar/index.en.md?type=text'),
  },
  'components/Calendar/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__Calendar__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Calendar/index.md?type=text'),
  },
  'components/Checkbox/index.en': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__Checkbox__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checkbox/index.en.md?type=text'),
  },
  'components/Checkbox/index': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__Checkbox" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checkbox/index.md?type=text'),
  },
  'components/Checklist/index.en': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__Checklist__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checklist/index.en.md?type=text'),
  },
  'components/Checklist/index': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__Checklist" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Checklist/index.md?type=text'),
  },
  'components/Collapse/index.en': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__Collapse__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Collapse/index.en.md?type=text'),
  },
  'components/Collapse/index': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__Collapse" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Collapse/index.md?type=text'),
  },
  'components/Container/index.en': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__Container__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Container/index.en.md?type=text'),
  },
  'components/Container/index': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__Container" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Container/index.md?type=text'),
  },
  'components/DatePicker/index.en': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__DatePicker__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/DatePicker/index.en.md?type=text'),
  },
  'components/DatePicker/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__DatePicker" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/DatePicker/index.md?type=text'),
  },
  'components/Divider/index.en': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__Divider__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Divider/index.en.md?type=text'),
  },
  'components/Divider/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__Divider" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Divider/index.md?type=text'),
  },
  'components/Empty/index.en': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__Empty__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Empty/index.en.md?type=text'),
  },
  'components/Empty/index': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__Empty" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Empty/index.md?type=text'),
  },
  'components/Form/index.en': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__Form__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Form/index.en.md?type=text'),
  },
  'components/Form/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__Form" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Form/index.md?type=text'),
  },
  'components/Grid/index.en': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__Grid__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Grid/index.en.md?type=text'),
  },
  'components/Grid/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__Grid" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Grid/index.md?type=text'),
  },
  'components/GuideTour/index.en': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__GuideTour__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/GuideTour/index.en.md?type=text'),
  },
  'components/GuideTour/index': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__GuideTour" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/GuideTour/index.md?type=text'),
  },
  'components/Icon/index.en': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__Icon__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Icon/index.en.md?type=text'),
  },
  'components/Icon/index': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__Icon" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Icon/index.md?type=text'),
  },
  'components/ImageUpload/index.en': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__ImageUpload__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ImageUpload/index.en.md?type=text'),
  },
  'components/ImageUpload/index': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__ImageUpload" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/ImageUpload/index.md?type=text'),
  },
  'components/IndexBar/index.en': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__IndexBar__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/IndexBar/index.en.md?type=text'),
  },
  'components/IndexBar/index': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__IndexBar" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/IndexBar/index.md?type=text'),
  },
  'components/Input/index.en': {
    frontmatter: fm56,
    toc: t56,
    demoIndex: dmi56,
    textGetter: () => import(/* webpackChunkName: "meta__Input__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Input/index.en.md?type=text'),
  },
  'components/Input/index': {
    frontmatter: fm57,
    toc: t57,
    demoIndex: dmi57,
    textGetter: () => import(/* webpackChunkName: "meta__Input" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Input/index.md?type=text'),
  },
  'components/List/index.en': {
    frontmatter: fm58,
    toc: t58,
    demoIndex: dmi58,
    textGetter: () => import(/* webpackChunkName: "meta__List__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/List/index.en.md?type=text'),
  },
  'components/List/index': {
    frontmatter: fm59,
    toc: t59,
    demoIndex: dmi59,
    textGetter: () => import(/* webpackChunkName: "meta__List" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/List/index.md?type=text'),
  },
  'components/Loading/index.en': {
    frontmatter: fm60,
    toc: t60,
    demoIndex: dmi60,
    textGetter: () => import(/* webpackChunkName: "meta__Loading__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Loading/index.en.md?type=text'),
  },
  'components/Loading/index': {
    frontmatter: fm61,
    toc: t61,
    demoIndex: dmi61,
    textGetter: () => import(/* webpackChunkName: "meta__Loading" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Loading/index.md?type=text'),
  },
  'components/Modal/index.en': {
    frontmatter: fm62,
    toc: t62,
    demoIndex: dmi62,
    textGetter: () => import(/* webpackChunkName: "meta__Modal__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Modal/index.en.md?type=text'),
  },
  'components/Modal/index': {
    frontmatter: fm63,
    toc: t63,
    demoIndex: dmi63,
    textGetter: () => import(/* webpackChunkName: "meta__Modal" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Modal/index.md?type=text'),
  },
  'components/NoticeBar/index.en': {
    frontmatter: fm64,
    toc: t64,
    demoIndex: dmi64,
    textGetter: () => import(/* webpackChunkName: "meta__NoticeBar__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NoticeBar/index.en.md?type=text'),
  },
  'components/NoticeBar/index': {
    frontmatter: fm65,
    toc: t65,
    demoIndex: dmi65,
    textGetter: () => import(/* webpackChunkName: "meta__NoticeBar" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NoticeBar/index.md?type=text'),
  },
  'components/NumberKeyboard/index.en': {
    frontmatter: fm66,
    toc: t66,
    demoIndex: dmi66,
    textGetter: () => import(/* webpackChunkName: "meta__NumberKeyboard__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NumberKeyboard/index.en.md?type=text'),
  },
  'components/NumberKeyboard/index': {
    frontmatter: fm67,
    toc: t67,
    demoIndex: dmi67,
    textGetter: () => import(/* webpackChunkName: "meta__NumberKeyboard" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/NumberKeyboard/index.md?type=text'),
  },
  'components/PageContainer/index.en': {
    frontmatter: fm68,
    toc: t68,
    demoIndex: dmi68,
    textGetter: () => import(/* webpackChunkName: "meta__PageContainer__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/PageContainer/index.en.md?type=text'),
  },
  'components/PageContainer/index': {
    frontmatter: fm69,
    toc: t69,
    demoIndex: dmi69,
    textGetter: () => import(/* webpackChunkName: "meta__PageContainer" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/PageContainer/index.md?type=text'),
  },
  'components/Picker/index.en': {
    frontmatter: fm70,
    toc: t70,
    demoIndex: dmi70,
    textGetter: () => import(/* webpackChunkName: "meta__Picker__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Picker/index.en.md?type=text'),
  },
  'components/Picker/index': {
    frontmatter: fm71,
    toc: t71,
    demoIndex: dmi71,
    textGetter: () => import(/* webpackChunkName: "meta__Picker" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Picker/index.md?type=text'),
  },
  'components/Popover/index.en': {
    frontmatter: fm72,
    toc: t72,
    demoIndex: dmi72,
    textGetter: () => import(/* webpackChunkName: "meta__Popover__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popover/index.en.md?type=text'),
  },
  'components/Popover/index': {
    frontmatter: fm73,
    toc: t73,
    demoIndex: dmi73,
    textGetter: () => import(/* webpackChunkName: "meta__Popover" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popover/index.md?type=text'),
  },
  'components/Popup/index.en': {
    frontmatter: fm74,
    toc: t74,
    demoIndex: dmi74,
    textGetter: () => import(/* webpackChunkName: "meta__Popup__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popup/index.en.md?type=text'),
  },
  'components/Popup/index': {
    frontmatter: fm75,
    toc: t75,
    demoIndex: dmi75,
    textGetter: () => import(/* webpackChunkName: "meta__Popup" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Popup/index.md?type=text'),
  },
  'components/Progress/index.en': {
    frontmatter: fm76,
    toc: t76,
    demoIndex: dmi76,
    textGetter: () => import(/* webpackChunkName: "meta__Progress__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Progress/index.en.md?type=text'),
  },
  'components/Progress/index': {
    frontmatter: fm77,
    toc: t77,
    demoIndex: dmi77,
    textGetter: () => import(/* webpackChunkName: "meta__Progress" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Progress/index.md?type=text'),
  },
  'components/Radio/index.en': {
    frontmatter: fm78,
    toc: t78,
    demoIndex: dmi78,
    textGetter: () => import(/* webpackChunkName: "meta__Radio__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Radio/index.en.md?type=text'),
  },
  'components/Radio/index': {
    frontmatter: fm79,
    toc: t79,
    demoIndex: dmi79,
    textGetter: () => import(/* webpackChunkName: "meta__Radio" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Radio/index.md?type=text'),
  },
  'components/RareWordsKeyboard/index.en': {
    frontmatter: fm80,
    toc: t80,
    demoIndex: dmi80,
    textGetter: () => import(/* webpackChunkName: "meta__RareWordsKeyboard__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/RareWordsKeyboard/index.en.md?type=text'),
  },
  'components/RareWordsKeyboard/index': {
    frontmatter: fm81,
    toc: t81,
    demoIndex: dmi81,
    textGetter: () => import(/* webpackChunkName: "meta__RareWordsKeyboard" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/RareWordsKeyboard/index.md?type=text'),
  },
  'components/Rate/index.en': {
    frontmatter: fm82,
    toc: t82,
    demoIndex: dmi82,
    textGetter: () => import(/* webpackChunkName: "meta__Rate__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Rate/index.en.md?type=text'),
  },
  'components/Rate/index': {
    frontmatter: fm83,
    toc: t83,
    demoIndex: dmi83,
    textGetter: () => import(/* webpackChunkName: "meta__Rate" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Rate/index.md?type=text'),
  },
  'components/Result/index.en': {
    frontmatter: fm84,
    toc: t84,
    demoIndex: dmi84,
    textGetter: () => import(/* webpackChunkName: "meta__Result__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Result/index.en.md?type=text'),
  },
  'components/Result/index': {
    frontmatter: fm85,
    toc: t85,
    demoIndex: dmi85,
    textGetter: () => import(/* webpackChunkName: "meta__Result" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Result/index.md?type=text'),
  },
  'components/Selector/index.en': {
    frontmatter: fm86,
    toc: t86,
    demoIndex: dmi86,
    textGetter: () => import(/* webpackChunkName: "meta__Selector__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Selector/index.en.md?type=text'),
  },
  'components/Selector/index': {
    frontmatter: fm87,
    toc: t87,
    demoIndex: dmi87,
    textGetter: () => import(/* webpackChunkName: "meta__Selector" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Selector/index.md?type=text'),
  },
  'components/Skeleton/index.en': {
    frontmatter: fm88,
    toc: t88,
    demoIndex: dmi88,
    textGetter: () => import(/* webpackChunkName: "meta__Skeleton__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Skeleton/index.en.md?type=text'),
  },
  'components/Skeleton/index': {
    frontmatter: fm89,
    toc: t89,
    demoIndex: dmi89,
    textGetter: () => import(/* webpackChunkName: "meta__Skeleton" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Skeleton/index.md?type=text'),
  },
  'components/Slider/index.en': {
    frontmatter: fm90,
    toc: t90,
    demoIndex: dmi90,
    textGetter: () => import(/* webpackChunkName: "meta__Slider__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Slider/index.en.md?type=text'),
  },
  'components/Slider/index': {
    frontmatter: fm91,
    toc: t91,
    demoIndex: dmi91,
    textGetter: () => import(/* webpackChunkName: "meta__Slider" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Slider/index.md?type=text'),
  },
  'components/Stepper/index.en': {
    frontmatter: fm92,
    toc: t92,
    demoIndex: dmi92,
    textGetter: () => import(/* webpackChunkName: "meta__Stepper__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Stepper/index.en.md?type=text'),
  },
  'components/Stepper/index': {
    frontmatter: fm93,
    toc: t93,
    demoIndex: dmi93,
    textGetter: () => import(/* webpackChunkName: "meta__Stepper" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Stepper/index.md?type=text'),
  },
  'components/Steps/index.en': {
    frontmatter: fm94,
    toc: t94,
    demoIndex: dmi94,
    textGetter: () => import(/* webpackChunkName: "meta__Steps__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Steps/index.en.md?type=text'),
  },
  'components/Steps/index': {
    frontmatter: fm95,
    toc: t95,
    demoIndex: dmi95,
    textGetter: () => import(/* webpackChunkName: "meta__Steps" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Steps/index.md?type=text'),
  },
  'components/SwipeAction/index.en': {
    frontmatter: fm96,
    toc: t96,
    demoIndex: dmi96,
    textGetter: () => import(/* webpackChunkName: "meta__SwipeAction__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/SwipeAction/index.en.md?type=text'),
  },
  'components/SwipeAction/index': {
    frontmatter: fm97,
    toc: t97,
    demoIndex: dmi97,
    textGetter: () => import(/* webpackChunkName: "meta__SwipeAction" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/SwipeAction/index.md?type=text'),
  },
  'components/Switch/index.en': {
    frontmatter: fm98,
    toc: t98,
    demoIndex: dmi98,
    textGetter: () => import(/* webpackChunkName: "meta__Switch__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Switch/index.en.md?type=text'),
  },
  'components/Switch/index': {
    frontmatter: fm99,
    toc: t99,
    demoIndex: dmi99,
    textGetter: () => import(/* webpackChunkName: "meta__Switch" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Switch/index.md?type=text'),
  },
  'components/TabBar/index.en': {
    frontmatter: fm100,
    toc: t100,
    demoIndex: dmi100,
    textGetter: () => import(/* webpackChunkName: "meta__TabBar__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/TabBar/index.en.md?type=text'),
  },
  'components/TabBar/index': {
    frontmatter: fm101,
    toc: t101,
    demoIndex: dmi101,
    textGetter: () => import(/* webpackChunkName: "meta__TabBar" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/TabBar/index.md?type=text'),
  },
  'components/Tabs/index.en': {
    frontmatter: fm102,
    toc: t102,
    demoIndex: dmi102,
    textGetter: () => import(/* webpackChunkName: "meta__Tabs__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tabs/index.en.md?type=text'),
  },
  'components/Tabs/index': {
    frontmatter: fm103,
    toc: t103,
    demoIndex: dmi103,
    textGetter: () => import(/* webpackChunkName: "meta__Tabs" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tabs/index.md?type=text'),
  },
  'components/Tag/index.en': {
    frontmatter: fm104,
    toc: t104,
    demoIndex: dmi104,
    textGetter: () => import(/* webpackChunkName: "meta__Tag__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tag/index.en.md?type=text'),
  },
  'components/Tag/index': {
    frontmatter: fm105,
    toc: t105,
    demoIndex: dmi105,
    textGetter: () => import(/* webpackChunkName: "meta__Tag" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Tag/index.md?type=text'),
  },
  'components/Toast/index.en': {
    frontmatter: fm106,
    toc: t106,
    demoIndex: dmi106,
    textGetter: () => import(/* webpackChunkName: "meta__Toast__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Toast/index.en.md?type=text'),
  },
  'components/Toast/index': {
    frontmatter: fm107,
    toc: t107,
    demoIndex: dmi107,
    textGetter: () => import(/* webpackChunkName: "meta__Toast" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Toast/index.md?type=text'),
  },
  'components/Typography/index.en': {
    frontmatter: fm108,
    toc: t108,
    demoIndex: dmi108,
    textGetter: () => import(/* webpackChunkName: "meta__Typography__en" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Typography/index.en.md?type=text'),
  },
  'components/Typography/index': {
    frontmatter: fm109,
    toc: t109,
    demoIndex: dmi109,
    textGetter: () => import(/* webpackChunkName: "meta__Typography" */'/Users/dennis.zhang/Desktop/服务商/ant-design-mini/src/Typography/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
