export var DatePickerDefaultProps = {
    visible: null,
    defaultVisible: null,
    animationType: 'transform',
    format: 'YYYY/MM/DD',
    min: null,
    max: null,
    value: null,
    defaultValue: null,
    title: '',
    okText: undefined,
    cancelText: undefined,
    placeholder: undefined,
    precision: 'day',
    maskClosable: true,
    popClassName: '',
    popStyle: '',
    disabled: false,
    onFormatLabel: null,
    onFormat: null,
};
