/**
 * Z字库离线数据
 */
export const ZDATAS = {
  version: '1.0.2',
  fontUrl: 'https://mdn.alipayobjects.com/huamei_2fq7mt/afts/file/A*Q1d6SY54amIAAAAAAAAAAAAADh58AQ/RareWordsFont-v1.0.2.ttf',
  datas: [
    {
      charId: 'fa95d0',
      unicodeChar: '𡹇',
      unicodeFont: 'null',
      unicodeCodePoint: '21E47',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LIN2' }],
      splitChars: [{ char: '山林' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'f87ad0',
      unicodeChar: '𤊟',
      unicodeFont: 'null',
      unicodeCodePoint: '2429F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TING3' }],
      splitChars: [{ char: '火定' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'fd1326',
      unicodeChar: '𨱑',
      unicodeFont: 'null',
      unicodeCodePoint: '28C51',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HUANG2' }],
      splitChars: [{ char: '钅黄' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '205583',
      unicodeChar: '𣲘',
      unicodeFont: 'null',
      unicodeCodePoint: '23C98',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WU3' }],
      splitChars: [{ char: '氵无' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '50d365',
      unicodeChar: '㗊',
      unicodeFont: 'null',
      unicodeCodePoint: '35CA',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JI2' }, { char: 'LEI2' }],
      splitChars: [{ char: '' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '18f13e',
      unicodeChar: '𬍡',
      unicodeFont: 'null',
      unicodeCodePoint: '2C361',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'DANG4' }],
      splitChars: [{ char: '汤玉' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '4e7341',
      unicodeChar: '䴙',
      unicodeFont: 'null',
      unicodeCodePoint: '4D19',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'PI4' }],
      splitChars: [{ char: '辟鸟' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '04abd1',
      unicodeChar: '𰞔',
      unicodeFont: 'null',
      unicodeCodePoint: '30794',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MI4' }],
      splitChars: [{ char: '火名' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '264ae4',
      unicodeChar: '䒟',
      unicodeFont: 'null',
      unicodeCodePoint: '449F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'DAN1' }],
      splitChars: [{ char: '艹丹' }, { char: '草丹' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'c97fbd',
      unicodeChar: '𥖄',
      unicodeFont: 'null',
      unicodeCodePoint: '25584',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XIAN4' }],
      splitChars: [{ char: '石羡' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '913adc',
      unicodeChar: '𪲔',
      unicodeFont: 'null',
      unicodeCodePoint: '2AC94',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LI4' }],
      splitChars: [{ char: '木丽' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'f80e2f',
      unicodeChar: '𢒉',
      unicodeFont: 'null',
      unicodeCodePoint: '22489',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHAN3' }],
      splitChars: [{ char: '彡且' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7cb879',
      unicodeChar: '𤧞',
      unicodeFont: 'null',
      unicodeCodePoint: '249DE',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MEI3' }],
      splitChars: [{ char: '王美' }, { char: '⺩美' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7dee10',
      unicodeChar: '𡌶',
      unicodeFont: 'null',
      unicodeCodePoint: '21336',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'BAN4' }],
      splitChars: [{ char: '土並' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2528dd',
      unicodeChar: '𰛥',
      unicodeFont: 'null',
      unicodeCodePoint: '306E5',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'AI2' }],
      splitChars: [{ char: '氵岂' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '0045c0',
      unicodeChar: '𤨾',
      unicodeFont: 'null',
      unicodeCodePoint: '24A3E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'KUN1' }],
      splitChars: [{ char: '王山昆' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'a70a3a',
      unicodeChar: '璟',
      unicodeFont: 'null',
      unicodeCodePoint: '749F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JING3' }],
      splitChars: [{ char: '王景' }, { char: '⺩景' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2e2e4f',
      unicodeChar: '䄻',
      unicodeFont: 'null',
      unicodeCodePoint: '413B',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHAO2' }, { char: 'TAO2' }, { char: 'ZHAO4' }],
      splitChars: [{ char: '禾兆' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'cd0140',
      unicodeChar: '𰬫',
      unicodeFont: 'null',
      unicodeCodePoint: '30B2B',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHI4' }],
      splitChars: [{ char: '纟致' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '94733c',
      unicodeChar: '𰽚',
      unicodeFont: 'null',
      unicodeCodePoint: '30F5A',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'KUANG4' }],
      splitChars: [{ char: '钅广' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '75c1f2',
      unicodeChar: '𫖮',
      unicodeFont: 'null',
      unicodeCodePoint: '2B5AE',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YI3' }],
      splitChars: [{ char: '岂页' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'f0f70c',
      unicodeChar: '㷧',
      unicodeFont: 'null',
      unicodeCodePoint: '3DE7',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YUAN2' }],
      splitChars: [{ char: '火原' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'f610f4',
      unicodeChar: '𬬸',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB38',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHU4' }],
      splitChars: [{ char: '钅术' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'e0c603',
      unicodeChar: '䵍',
      unicodeFont: 'null',
      unicodeCodePoint: '4D4D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TUN2' }],
      splitChars: [{ char: '黄享' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '97fa5d',
      unicodeChar: '𤆬',
      unicodeFont: 'null',
      unicodeCodePoint: '241AC',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QU3' }],
      splitChars: [{ char: '毛灬' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '36d00c',
      unicodeChar: '㚢',
      unicodeFont: 'null',
      unicodeCodePoint: '36A2',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WU3' }, { char: 'NU2' }, { char: 'NV3' }],
      splitChars: [{ char: '亻女' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '4b8f40',
      unicodeChar: '堃',
      unicodeFont: 'null',
      unicodeCodePoint: '5803',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'KUN1' }],
      splitChars: [{ char: '方方土' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'a0c29d',
      unicodeChar: '䴔',
      unicodeFont: 'null',
      unicodeCodePoint: '4D14',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JIAO1' }],
      splitChars: [{ char: '交鸟' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2bce53',
      unicodeChar: '㐵',
      unicodeFont: 'null',
      unicodeCodePoint: '3435',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'RU2' }],
      splitChars: [{ char: '亻于' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b01882',
      unicodeChar: '䝼',
      unicodeFont: 'null',
      unicodeCodePoint: '477C',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QING2' }],
      splitChars: [{ char: '貝青' }, { char: '贝青' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2337c3',
      unicodeChar: '𬎆',
      unicodeFont: 'null',
      unicodeCodePoint: '2C386',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YING2' }],
      splitChars: [{ char: '王莹' }, { char: '⺩莹' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'f76202',
      unicodeChar: '𪸕',
      unicodeFont: 'null',
      unicodeCodePoint: '2AE15',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XI4' }],
      splitChars: [{ char: '火气' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '3796ee',
      unicodeChar: '𬱖',
      unicodeFont: 'null',
      unicodeCodePoint: '2CC56',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'DI2' }],
      splitChars: [{ char: '由页' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '62877c',
      unicodeChar: '𫢒',
      unicodeFont: 'null',
      unicodeCodePoint: '2B892',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LONG2' }, { char: 'LONG3' }, { char: 'LONG4' }],
      splitChars: [{ char: '亻龙' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7aef30',
      unicodeChar: '',
      unicodeFont: 'null',
      unicodeCodePoint: 'null',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LI4' }],
      splitChars: [{ char: '⺩丽' }, { char: '王丽' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '246507',
      unicodeChar: '𬱟',
      unicodeFont: 'null',
      unicodeCodePoint: '2CC5F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI2' }],
      splitChars: [{ char: '危页' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '064f5d',
      unicodeChar: '𬴂',
      unicodeFont: 'null',
      unicodeCodePoint: '2CD02',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'FEI1' }],
      splitChars: [{ char: '马非' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '185e8f',
      unicodeChar: '䦷',
      unicodeFont: 'null',
      unicodeCodePoint: '49B7',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHUAI4' }],
      splitChars: [{ char: '门坐' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'd18a6f',
      unicodeChar: '㛠',
      unicodeFont: 'null',
      unicodeCodePoint: '36E0',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JIAN1' }, { char: 'XIAN2' }],
      splitChars: [{ char: '女间' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7e4d31',
      unicodeChar: '𬮦',
      unicodeFont: 'null',
      unicodeCodePoint: '2CBA6',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GUAN1' }],
      splitChars: [{ char: '门关' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'dd3cd3',
      unicodeChar: '𤰉',
      unicodeFont: 'null',
      unicodeCodePoint: '24C09',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YONG1' }, { char: 'LA2' }],
      splitChars: [{ char: '足用' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2fd545',
      unicodeChar: '𬈜',
      unicodeFont: 'null',
      unicodeCodePoint: '2C21C',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YING2' }],
      splitChars: [{ char: '氵荥' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'd1508c',
      unicodeChar: '𱯍',
      unicodeFont: 'null',
      unicodeCodePoint: '31BCD',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GE1' }],
      splitChars: [{ char: '⺩哥' }, { char: '王哥' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '974f5d',
      unicodeChar: '𪩘',
      unicodeFont: 'null',
      unicodeCodePoint: '2AA58',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YAN3' }],
      splitChars: [{ char: '山献' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b93b09',
      unicodeChar: '㑇',
      unicodeFont: 'null',
      unicodeCodePoint: '3447',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHOU1' }],
      splitChars: [{ char: '人刍' }, { char: '亻刍' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'b74cec',
      unicodeChar: '㻌',
      unicodeFont: 'null',
      unicodeCodePoint: '3ECC',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHU1' }, { char: 'TU2' }],
      splitChars: [{ char: '王余' }, { char: '⺩余' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'ae78ce',
      unicodeChar: '琤',
      unicodeFont: 'null',
      unicodeCodePoint: '7424',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHENG1' }],
      splitChars: [{ char: '⺩争' }, { char: '王争' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7b7ee0',
      unicodeChar: '𱃚',
      unicodeFont: 'null',
      unicodeCodePoint: '310DA',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XIE2' }, { char: 'LIE4' }, { char: 'LI4' }],
      splitChars: [{ char: '风劦' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b575d0',
      unicodeChar: '𠅤',
      unicodeFont: 'null',
      unicodeCodePoint: '20164',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XI1' }],
      splitChars: [{ char: '亠思' }, { char: '亩心' }, { char: '二思' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '8eff88',
      unicodeChar: '𤧟',
      unicodeFont: 'null',
      unicodeCodePoint: '249DF',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TING2' }],
      splitChars: [{ char: '王亭' }, { char: '⺩亭' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'c9cc46',
      unicodeChar: '𫵳',
      unicodeFont: 'null',
      unicodeCodePoint: '2BD73',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JI1' }],
      splitChars: [{ char: '山几' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '65fb41',
      unicodeChar: '𫞦',
      unicodeFont: 'null',
      unicodeCodePoint: '2B7A6',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JI4' }, { char: 'ZI1' }],
      splitChars: [{ char: '⺩齐' }, { char: '王齐' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b0f9cb',
      unicodeChar: '𤆵',
      unicodeFont: 'null',
      unicodeCodePoint: '241B5',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'PA1' }],
      splitChars: [{ char: '火巴' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '81998b',
      unicodeChar: '㑳',
      unicodeFont: 'null',
      unicodeCodePoint: '3473',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHOU4' }],
      splitChars: [{ char: '亻芻' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'cda910',
      unicodeChar: '㛃',
      unicodeFont: 'null',
      unicodeCodePoint: '36C3',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JIE2' }],
      splitChars: [{ char: '㓞女' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'cd99fb',
      unicodeChar: '㞧',
      unicodeFont: 'null',
      unicodeCodePoint: '37A7',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HUI4' }],
      splitChars: [{ char: '山乃' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '1738a3',
      unicodeChar: '𬊍',
      unicodeFont: 'null',
      unicodeCodePoint: '2C28D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHOU2' }],
      splitChars: [{ char: '火寿' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '816ac4',
      unicodeChar: '𬇙',
      unicodeFont: 'null',
      unicodeCodePoint: '2C1D9',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'PEI4' }],
      splitChars: [{ char: '氵贝' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '593f33',
      unicodeChar: '𫵷',
      unicodeFont: 'null',
      unicodeCodePoint: '2BD77',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LI4' }, { char: 'LAI4' }],
      splitChars: [{ char: '山历' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '1ef9de',
      unicodeChar: '𬱵',
      unicodeFont: 'null',
      unicodeCodePoint: '2CC75',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI3' }],
      splitChars: [{ char: '风韦' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'b47214',
      unicodeChar: '𬮿',
      unicodeFont: 'null',
      unicodeCodePoint: '2CBBF',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GAI1' }, { char: 'QI1' }, { char: 'AI2' }],
      splitChars: [{ char: '阝岂' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'f6db38',
      unicodeChar: '𪻐',
      unicodeFont: 'null',
      unicodeCodePoint: '2AED0',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CONG1' }],
      splitChars: [{ char: '⺩从' }, { char: '王从' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'e01b87',
      unicodeChar: '𫞡',
      unicodeFont: 'null',
      unicodeCodePoint: '2B7A1',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'RONG2' }],
      splitChars: [{ char: '火荣' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '278c8f',
      unicodeChar: '𬍑',
      unicodeFont: 'null',
      unicodeCodePoint: '2C351',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHAN1' }],
      splitChars: [{ char: '⺩山' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '81355f',
      unicodeChar: '玥',
      unicodeFont: 'null',
      unicodeCodePoint: '73A5',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YUE4' }],
      splitChars: [{ char: '王月' }, { char: '⺩月' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '997e29',
      unicodeChar: '𲊿',
      unicodeFont: 'null',
      unicodeCodePoint: '322BF',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XIAN3' }],
      splitChars: [{ char: '显页' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '4b5c44',
      unicodeChar: '𫰡',
      unicodeFont: 'null',
      unicodeCodePoint: '2BC21',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HUA4' }],
      splitChars: [{ char: '女华' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '57a0a1',
      unicodeChar: '𪠽',
      unicodeFont: 'null',
      unicodeCodePoint: '2A83D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'DANG1' }],
      splitChars: [{ char: '口当' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '4e9967',
      unicodeChar: '𣲗',
      unicodeFont: 'null',
      unicodeCodePoint: '23C97',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI2' }],
      splitChars: [{ char: '氵韦' }, { char: '水韦' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '2baf46',
      unicodeChar: '彧',
      unicodeFont: 'null',
      unicodeCodePoint: '5F67',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YU4' }],
      splitChars: [{ char: '' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '66c867',
      unicodeChar: '䶮',
      unicodeFont: 'null',
      unicodeCodePoint: '4DAE',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YAN3' }],
      splitChars: [{ char: '龙天' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '5ab6cf',
      unicodeChar: '𬞟',
      unicodeFont: 'null',
      unicodeCodePoint: '2C79F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'PIN2' }, { char: 'PING2' }],
      splitChars: [{ char: '艹频' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'e7a9b2',
      unicodeChar: '𬬿',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB3F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHAO1' }],
      splitChars: [{ char: '钅召' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'd4153a',
      unicodeChar: '𫢸',
      unicodeFont: 'null',
      unicodeCodePoint: '2B8B8',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'DAN4' }],
      splitChars: [{ char: '亻单' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '6e9449',
      unicodeChar: '㳠',
      unicodeFont: 'null',
      unicodeCodePoint: '3CE0',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TA4' }],
      splitChars: [{ char: '氵达' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'd98817',
      unicodeChar: '𰎠',
      unicodeFont: 'null',
      unicodeCodePoint: '303A0',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YAN2' }],
      splitChars: [{ char: '山严' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'c82379',
      unicodeChar: '',
      unicodeFont: 'null',
      unicodeCodePoint: 'null',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUN1' }],
      splitChars: [{ char: '勋灬' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '84c3c9',
      unicodeChar: '𬀩',
      unicodeFont: 'null',
      unicodeCodePoint: '2C029',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI3' }],
      splitChars: [{ char: '日韦' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '95e719',
      unicodeChar: '𮭦',
      unicodeFont: 'null',
      unicodeCodePoint: '2EB66',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHEN2' }],
      splitChars: [{ char: '岑鸟' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '44775c',
      unicodeChar: '㻑',
      unicodeFont: 'null',
      unicodeCodePoint: '3ED1',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JI4' }],
      splitChars: [{ char: '王季' }, { char: '⺩季' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '199018',
      unicodeChar: '䫺',
      unicodeFont: 'null',
      unicodeCodePoint: '4AFA',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HOU4' }, { char: 'HONG2' }],
      splitChars: [{ char: '厷风' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '971908',
      unicodeChar: '𰵧',
      unicodeFont: 'null',
      unicodeCodePoint: '30D67',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHI4' }],
      splitChars: [{ char: '讠志' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'c48f08',
      unicodeChar: '𮣳',
      unicodeFont: 'null',
      unicodeCodePoint: '2E8F3',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GONG1' }, { char: 'HONG2' }],
      splitChars: [{ char: '金厷' }, { char: '钅厷' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '8ee75e',
      unicodeChar: '䴖',
      unicodeFont: 'null',
      unicodeCodePoint: '4D16',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JING1' }],
      splitChars: [{ char: '青鸟' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '6cf248',
      unicodeChar: '䴓',
      unicodeFont: 'null',
      unicodeCodePoint: '4D13',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHI1' }],
      splitChars: [{ char: '帀鸟' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2b2ec1',
      unicodeChar: '𨱇',
      unicodeFont: 'null',
      unicodeCodePoint: '28C47',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QIU2' }],
      splitChars: [{ char: '钅求' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '081b01',
      unicodeChar: '𰵝',
      unicodeFont: 'null',
      unicodeCodePoint: '30D5D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HE2' }],
      splitChars: [{ char: '讠禾' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '03e311',
      unicodeChar: '𪿖',
      unicodeFont: 'null',
      unicodeCodePoint: '2AFD6',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TAN2' }],
      splitChars: [{ char: '石玄' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'c0c451',
      unicodeChar: '',
      unicodeFont: 'null',
      unicodeCodePoint: 'null',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YE4' }],
      splitChars: [{ char: '王华' }, { char: '⺩华' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '1fd65a',
      unicodeChar: '䜣',
      unicodeFont: 'null',
      unicodeCodePoint: '4723',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XIN1' }, { char: 'YIN2' }, { char: 'XI1' }],
      splitChars: [{ char: '讠斤' }, { char: '言斤' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '903102',
      unicodeChar: '焜',
      unicodeFont: 'null',
      unicodeCodePoint: '711C',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'KUN1' }],
      splitChars: [{ char: '火昆' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '796a7e',
      unicodeChar: '㻿',
      unicodeFont: 'null',
      unicodeCodePoint: '3EFF',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHU3' }],
      splitChars: [{ char: '⺩蜀' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2006a3',
      unicodeChar: '𤩽',
      unicodeFont: 'null',
      unicodeCodePoint: '24A7D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HUAN2' }],
      splitChars: [{ char: '王献' }, { char: '⺩献' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'a6819c',
      unicodeChar: '𰎝',
      unicodeFont: 'null',
      unicodeCodePoint: '3039D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HUN2' }, { char: 'JUN1' }],
      splitChars: [{ char: '山军' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'e4ca07',
      unicodeChar: '㛇',
      unicodeFont: 'null',
      unicodeCodePoint: '36C7',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHUANG1' }],
      splitChars: [{ char: '女庄' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '61fbef',
      unicodeChar: '𱔐',
      unicodeFont: 'null',
      unicodeCodePoint: '31510',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QI3' }],
      splitChars: [{ char: '啟口' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '1658b6',
      unicodeChar: '禤',
      unicodeFont: 'null',
      unicodeCodePoint: '79A4',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUAN1' }],
      splitChars: [{ char: '衣四羽' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '359bde',
      unicodeChar: '𨱎',
      unicodeFont: 'null',
      unicodeCodePoint: '28C4E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TOU1' }],
      splitChars: [{ char: '钅俞' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '22759d',
      unicodeChar: '𪨶',
      unicodeFont: 'null',
      unicodeCodePoint: '2AA36',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHE1' }],
      splitChars: [{ char: '山大车' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '96477d',
      unicodeChar: '𬳳',
      unicodeFont: 'null',
      unicodeCodePoint: '2CCF3',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'FAN1' }],
      splitChars: [{ char: '马风' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '0b35aa',
      unicodeChar: '𬬺',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB3A',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JU3' }, { char: 'CHU2' }, { char: 'ZU1' }, { char: 'XU2' }],
      splitChars: [{ char: '钅且' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '5f7627',
      unicodeChar: '䦶',
      unicodeFont: 'null',
      unicodeCodePoint: '49B3',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHENG4' }, { char: 'ZHI4' }],
      splitChars: [{ char: '门争' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '9a6923',
      unicodeChar: '𰾫',
      unicodeFont: 'null',
      unicodeCodePoint: '30FAB',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JIAN4' }],
      splitChars: [{ char: '钅监' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'fd164b',
      unicodeChar: '𬭣',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB63',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XIAN4' }],
      splitChars: [{ char: '钅泉' }, { char: '金泉' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '12f378',
      unicodeChar: '𬭚',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB5A',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHUN2' }],
      splitChars: [{ char: '钅享' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '80d8d5',
      unicodeChar: '𡸃',
      unicodeFont: 'null',
      unicodeCodePoint: '21E03',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QIAN1' }],
      splitChars: [{ char: '山佥' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '597805',
      unicodeChar: '𡵓',
      unicodeFont: 'null',
      unicodeCodePoint: '21D53',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HONG2' }],
      splitChars: [{ char: '山厷' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'daba78',
      unicodeChar: '𡷫',
      unicodeFont: 'null',
      unicodeCodePoint: '21DEB',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHENG2' }],
      splitChars: [{ char: '山成' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'c04d91',
      unicodeChar: '𫟹',
      unicodeFont: 'null',
      unicodeCodePoint: '2B7F9',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HONG2' }],
      splitChars: [{ char: '钅共' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '784534',
      unicodeChar: '𱪿',
      unicodeFont: 'null',
      unicodeCodePoint: 'null',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUN1' }],
      splitChars: [{ char: '动灬' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'f11765',
      unicodeChar: '滢',
      unicodeFont: 'null',
      unicodeCodePoint: '6EE2',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YING2' }],
      splitChars: [{ char: '' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '0dbd6a',
      unicodeChar: '𡛓',
      unicodeFont: 'null',
      unicodeCodePoint: '216D3',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'RAN3' }],
      splitChars: [{ char: '女丹' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '00267b',
      unicodeChar: '𠇔',
      unicodeFont: 'null',
      unicodeCodePoint: '201D4',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TUO1' }],
      splitChars: [{ char: '亻毛' }, { char: '人毛' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '4d9080',
      unicodeChar: '𲇷',
      unicodeFont: 'null',
      unicodeCodePoint: '321F7',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LIAN4' }],
      splitChars: [{ char: '钅东' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'dbf23c',
      unicodeChar: '𫝫',
      unicodeFont: 'null',
      unicodeCodePoint: '2B76B',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LAI4' }, { char: 'LAI1' }],
      splitChars: [{ char: '女来' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '060dd4',
      unicodeChar: '𬘬',
      unicodeFont: 'null',
      unicodeCodePoint: '2C62C',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QING1' }, { char: 'ZHENG1' }],
      splitChars: [{ char: '纟青' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '1968a4',
      unicodeChar: '𫰍',
      unicodeFont: 'null',
      unicodeCodePoint: '2BC0D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI2' }, { char: 'WEI3' }],
      splitChars: [{ char: '女韦' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '6b0040',
      unicodeChar: '垚',
      unicodeFont: 'null',
      unicodeCodePoint: '579A',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YAO2' }],
      splitChars: [{ char: '土土土' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '1bf322',
      unicodeChar: '𬍛',
      unicodeFont: 'null',
      unicodeCodePoint: '2C35B',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LI4' }],
      splitChars: [{ char: '⺩乐' }, { char: '王乐' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'da00b5',
      unicodeChar: '𱮺',
      unicodeFont: 'null',
      unicodeCodePoint: '31BBA',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TIAN1' }, { char: 'ZHEN1' }],
      splitChars: [{ char: '王贞' }, { char: '⺩贞' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'f97ba6',
      unicodeChar: '𫖯',
      unicodeFont: 'null',
      unicodeCodePoint: '2B5AF',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'FU3' }, { char: 'TAO1' }, { char: 'TIAO44' }],
      splitChars: [{ char: '兆页' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '3b3969',
      unicodeChar: '𪜔',
      unicodeFont: 'null',
      unicodeCodePoint: '2A714',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QU3' }],
      splitChars: [{ char: '九曲' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'bc8447',
      unicodeChar: '𡝗',
      unicodeFont: 'null',
      unicodeCodePoint: '21757',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QUN2' }, { char: 'JUN1' }],
      splitChars: [{ char: '女君' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '22b6df',
      unicodeChar: '㐱',
      unicodeFont: 'null',
      unicodeCodePoint: '3431',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZHEN1' }],
      splitChars: [{ char: '' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7fd1d4',
      unicodeChar: '䁎',
      unicodeFont: 'null',
      unicodeCodePoint: '404E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHENG2' }, { char: 'TING2' }],
      splitChars: [{ char: '目亭' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '121889',
      unicodeChar: '煇',
      unicodeFont: 'null',
      unicodeCodePoint: '7147',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUN1' }, { char: 'YUN44' }, { char: 'HUI1' }],
      splitChars: [{ char: '火军' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'e581cd',
      unicodeChar: '',
      unicodeFont: 'null',
      unicodeCodePoint: 'null',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YI2' }],
      splitChars: [{ char: '王臣' }, { char: '⺩臣' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2efd07',
      unicodeChar: '㶲',
      unicodeFont: 'null',
      unicodeCodePoint: '3DB2',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YONG4' }],
      splitChars: [{ char: '火用' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '18e173',
      unicodeChar: '𬜬',
      unicodeFont: 'null',
      unicodeCodePoint: '2C72C',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MAN4' }],
      splitChars: [{ char: '艹问' }, { char: '草问' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '9bb1f9',
      unicodeChar: '𫘛',
      unicodeFont: 'null',
      unicodeCodePoint: '2B61B',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HAN2' }, { char: 'HAN4' }],
      splitChars: [{ char: '马干' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'd49bf3',
      unicodeChar: '𠊟',
      unicodeFont: 'null',
      unicodeCodePoint: '2029F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MIN3' }],
      splitChars: [{ char: '亻黾' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '72757b',
      unicodeChar: '𱂐',
      unicodeFont: 'null',
      unicodeCodePoint: '31090',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YUN4' }],
      splitChars: [{ char: '音员' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '91f144',
      unicodeChar: '𰵞',
      unicodeFont: 'null',
      unicodeCodePoint: '30D5E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YONG1' }],
      splitChars: [{ char: '讠永' }, { char: '言永' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'a74408',
      unicodeChar: '𰤕',
      unicodeFont: 'null',
      unicodeCodePoint: '30915',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LUO4' }, { char: 'LI4' }],
      splitChars: [{ char: '白乐' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'e95ed7',
      unicodeChar: '𪨧',
      unicodeFont: 'null',
      unicodeCodePoint: '2AA27',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LUN2' }],
      splitChars: [{ char: '山仑' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '85360b',
      unicodeChar: '𫔭',
      unicodeFont: 'null',
      unicodeCodePoint: '2B52D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'KAI1' }],
      splitChars: [{ char: '门开' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'ddf4aa',
      unicodeChar: '𣑮',
      unicodeFont: 'null',
      unicodeCodePoint: '2346E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'NAN2' }],
      splitChars: [{ char: '木舟' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '30b346',
      unicodeChar: '㧏',
      unicodeFont: 'null',
      unicodeCodePoint: '39CF',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GANG1' }],
      splitChars: [{ char: '扌冈' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '9dc76c',
      unicodeChar: '𨭉',
      unicodeFont: 'null',
      unicodeCodePoint: '28B49',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'BAN1' }],
      splitChars: [{ char: '斌金' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '0729be',
      unicodeChar: '𬊈',
      unicodeFont: 'null',
      unicodeCodePoint: '2C288',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUN2' }],
      splitChars: [{ char: '火寻' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '012f02',
      unicodeChar: '㶥',
      unicodeFont: 'null',
      unicodeCodePoint: '3DA5',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GAN1' }],
      splitChars: [{ char: '火干' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '5552a2',
      unicodeChar: '𣛮',
      unicodeFont: 'null',
      unicodeCodePoint: '236EE',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'SHENG1' }],
      splitChars: [{ char: '木盛' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '774a78',
      unicodeChar: '㭎',
      unicodeFont: 'null',
      unicodeCodePoint: '3B4E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GANG1' }],
      splitChars: [{ char: '木冈' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'ecefb5',
      unicodeChar: '晔',
      unicodeFont: 'null',
      unicodeCodePoint: '6654',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YE4' }],
      splitChars: [{ char: '日华' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '5c4e1f',
      unicodeChar: '旻',
      unicodeFont: 'null',
      unicodeCodePoint: '65FB',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MIN2' }],
      splitChars: [{ char: '日文' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7f9254',
      unicodeChar: '𤎌',
      unicodeFont: 'null',
      unicodeCodePoint: '2438C',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'TANG2' }],
      splitChars: [{ char: '火堂' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '755ea6',
      unicodeChar: '𬮤',
      unicodeFont: 'null',
      unicodeCodePoint: '2CBA4',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HE2' }, { char: 'GE2' }, { char: 'XIA2' }],
      splitChars: [{ char: '门合' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '9b123e',
      unicodeChar: '𬬲',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB32',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'PI1' }, { char: 'ZHAO1' }],
      splitChars: [{ char: '钅爪' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '155a4c',
      unicodeChar: '㻴',
      unicodeFont: 'null',
      unicodeCodePoint: '3EF4',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MAN4' }],
      splitChars: [{ char: '王曼' }, { char: '⺩曼' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2930db',
      unicodeChar: '𫍽',
      unicodeFont: 'null',
      unicodeCodePoint: '2B37D',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUAN1' }],
      splitChars: [{ char: '言睘' }, { char: '讠睘' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'd88cab',
      unicodeChar: '𮧵',
      unicodeFont: 'null',
      unicodeCodePoint: '2E9F5',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI3' }],
      splitChars: [{ char: '韦华' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'defed4',
      unicodeChar: '',
      unicodeFont: 'null',
      unicodeCodePoint: 'null',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: '' }],
      splitChars: [{ char: '忄风' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '752b10',
      unicodeChar: '㞭',
      unicodeFont: 'null',
      unicodeCodePoint: '37AD',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'DAI2' }],
      splitChars: [{ char: '大山' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2da6b3',
      unicodeChar: '㙟',
      unicodeFont: 'null',
      unicodeCodePoint: '365F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LANG3' }],
      splitChars: [{ char: '土朗' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '5b55cd',
      unicodeChar: '燚',
      unicodeFont: 'null',
      unicodeCodePoint: '71DA',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YI4' }],
      splitChars: [{ char: '火火火火' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '72ddd3',
      unicodeChar: '𨰻',
      unicodeFont: 'null',
      unicodeCodePoint: '28C3B',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YU4' }, { char: 'BAO3' }],
      splitChars: [{ char: '金金金金' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '52f09e',
      unicodeChar: '𫲦',
      unicodeFont: 'null',
      unicodeCodePoint: '2BCA6',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MAN3' }],
      splitChars: [{ char: '子兑' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '4f3c62',
      unicodeChar: '竑',
      unicodeFont: 'null',
      unicodeCodePoint: '7AD1',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HONG2' }],
      splitChars: [{ char: '立厷' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'a25c47',
      unicodeChar: '𰽦',
      unicodeFont: 'null',
      unicodeCodePoint: '30F66',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LONG2' }],
      splitChars: [{ char: '钅龙' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '5b5ed6',
      unicodeChar: '䳟',
      unicodeFont: 'null',
      unicodeCodePoint: '4CDF',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'MING2' }],
      splitChars: [{ char: '明鸟' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '0ce2a5',
      unicodeChar: '𫘧',
      unicodeFont: 'null',
      unicodeCodePoint: '2B627',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LU4' }],
      splitChars: [{ char: '马录' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '9427be',
      unicodeChar: '𬀪',
      unicodeFont: 'null',
      unicodeCodePoint: '2C02A',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XIAN1' }],
      splitChars: [{ char: '日见' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'd7d7b1',
      unicodeChar: '樑',
      unicodeFont: 'null',
      unicodeCodePoint: '6A11',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LIANG1' }],
      splitChars: [{ char: '' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'fa6662',
      unicodeChar: '㢨',
      unicodeFont: 'null',
      unicodeCodePoint: '38A8',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HAN4' }],
      splitChars: [{ char: '弓干' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'fd1073',
      unicodeChar: '𬭎',
      unicodeFont: 'null',
      unicodeCodePoint: '92D0',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HONG2' }],
      splitChars: [{ char: '钅宏' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b7232e',
      unicodeChar: '㺭',
      unicodeFont: 'null',
      unicodeCodePoint: '3EAD',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZI3' }],
      splitChars: [{ char: '⺩子' }, { char: '王子' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: '157d20',
      unicodeChar: '𱣉',
      unicodeFont: 'null',
      unicodeCodePoint: '318C9',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'ZONG1' }, { char: 'CONG1' }],
      splitChars: [{ char: '木丛' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '2c64ee',
      unicodeChar: '𬬬',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB2C',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI2' }],
      splitChars: [{ char: '钅韦' }, { char: '金韦' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'd7bc9c',
      unicodeChar: '',
      unicodeFont: 'null',
      unicodeCodePoint: 'E625',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'PENG1' }],
      splitChars: [{ char: '木木木木' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '9def2c',
      unicodeChar: '𠡠',
      unicodeFont: 'null',
      unicodeCodePoint: '20860',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHI1' }],
      splitChars: [{ char: '来力' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b84eaf',
      unicodeChar: '𩇕',
      unicodeFont: 'null',
      unicodeCodePoint: '291D5',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JING4' }],
      splitChars: [{ char: '青彡' }, { char: '靑彡' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '82846f',
      unicodeChar: '㧑',
      unicodeFont: 'null',
      unicodeCodePoint: '39D1',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'HUI1' }],
      splitChars: [{ char: '扌为' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7e3793',
      unicodeChar: '䓫',
      unicodeFont: 'null',
      unicodeCodePoint: '44EB',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QI2' }],
      splitChars: [{ char: '艹奇' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b26bb6',
      unicodeChar: '㮾',
      unicodeFont: 'null',
      unicodeCodePoint: '3BBE',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LANG3' }],
      splitChars: [{ char: '朗木' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b3c669',
      unicodeChar: '𬍤',
      unicodeFont: 'null',
      unicodeCodePoint: '2C364',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUN2' }],
      splitChars: [{ char: '王寻' }, { char: '⺩寻' }],
      weight: 10,
      extInfo: 'null',
    },
    {
      charId: 'a50d8e',
      unicodeChar: '冄',
      unicodeFont: 'null',
      unicodeCodePoint: '5184',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'RAN2' }],
      splitChars: [{ char: '' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '5e785e',
      unicodeChar: '𪛞',
      unicodeFont: 'null',
      unicodeCodePoint: '2A6DE',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'RONG2' }],
      splitChars: [{ char: '王荣' }, { char: '⺩荣' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '7d9ae0',
      unicodeChar: '珣',
      unicodeFont: 'null',
      unicodeCodePoint: '73E3',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'XUN2' }],
      splitChars: [{ char: '⺩旬' }, { char: '王旬' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'f1dd1c',
      unicodeChar: '𬬱',
      unicodeFont: 'null',
      unicodeCodePoint: '2CB31',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'JIN1' }],
      splitChars: [{ char: '钅斤' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '33ea1d',
      unicodeChar: '㳇',
      unicodeFont: 'null',
      unicodeCodePoint: '3CC7',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'FU2' }, { char: 'FU4' }],
      splitChars: [{ char: '氵父' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '17d572',
      unicodeChar: '𬴀',
      unicodeFont: 'null',
      unicodeCodePoint: '2CD00',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LIANG2' }],
      splitChars: [{ char: '马良' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'cc2b4b',
      unicodeChar: '𱎞',
      unicodeFont: 'null',
      unicodeCodePoint: '3139E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WEI4' }],
      splitChars: [{ char: '亻卫' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '1c3f6b',
      unicodeChar: '𬇕',
      unicodeFont: 'null',
      unicodeCodePoint: '2C1D5',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'WAN4' }, { char: 'MAN4' }],
      splitChars: [{ char: '氵万' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '94faf7',
      unicodeChar: '𪨰',
      unicodeFont: 'null',
      unicodeCodePoint: '2AA30',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'QU1' }],
      splitChars: [{ char: '山曲' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '299be8',
      unicodeChar: '𰽥',
      unicodeFont: 'null',
      unicodeCodePoint: '30F65',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'BING3' }],
      splitChars: [{ char: '钅丙' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'b443a7',
      unicodeChar: '𬊤',
      unicodeFont: 'null',
      unicodeCodePoint: '2C2A4',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'CHAN3' }, { char: 'DAN1' }, { char: 'CHAN4' }],
      splitChars: [{ char: '火单' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '5c54ef',
      unicodeChar: '',
      unicodeFont: 'null',
      unicodeCodePoint: 'null',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YANG2' }],
      splitChars: [{ char: '风易' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '24acd3',
      unicodeChar: '𰎐',
      unicodeFont: 'null',
      unicodeCodePoint: '30390',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LU2' }],
      splitChars: [{ char: '山卢' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: '0f89b2',
      unicodeChar: '𬇹',
      unicodeFont: 'null',
      unicodeCodePoint: '2C1F9',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'GUO2' }],
      splitChars: [{ char: '氵国' }],
      weight: 8,
      extInfo: 'null',
    },
    {
      charId: 'db6725',
      unicodeChar: '𫗇',
      unicodeFont: 'null',
      unicodeCodePoint: '2B5C7',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'YU4' }, { char: 'XUE2' }],
      splitChars: [{ char: '风日' }],
      weight: 8,
      extInfo: 'null',
    },
  ],
};
