export var TextareaDefaultProps = {
    enableNative: false,
};
export var TextareaFunctionalProps = {
    value: null,
    defaultValue: null,
    placeholder: null,
    placeholderClassName: null,
    placeholderStyle: null,
    autoHeight: null,
    showCount: null,
    allowClear: null,
    controlled: null,
    enableNative: false,
    inputClassName: null,
    disabled: null,
    inputStyle: null,
    focusStyle: null,
    name: null,
    confirmType: null,
    focus: null,
    confirmHold: null,
    focusClassName: null,
    maxLength: -1,
    showConfirmBar: true,
    holdKeyboard: false,
    disableDefaultPadding: false,
    adjustKeyboardTo: 'cursor',
};
