export const InputItemDefaultProps = {
  controlled: false,
  type: 'text',
  password: false,
  maxLength: 140,
  confirmType: 'done',
  confirmHold: false,
  selectionStart: -1,
  selectionEnd: -1,
  randomNumber: false,
  alwaysSystem: false,
  clear: true,
  autoFocus: false,
  disabled: false,
};
