export var CascaderDefaultProps = {
    visible: null,
    defaultVisible: null,
    animationType: 'transform',
    value: null,
    defaultValue: null,
    options: [],
    placeholder: '请选择',
    cancelText: '取消',
    disabled: false,
    title: '',
    okText: '确定',
    maskClosable: true,
    popClassName: '',
    popStyle: '',
    onFormat: null,
};
