export var PickerDefaultProps = {
    formattedValueText: null,
    visible: null,
    defaultVisible: null,
    animationType: 'transform',
    value: null,
    defaultValue: null,
    disabled: false,
    title: '',
    okText: '确定',
    cancelText: '取消',
    placeholder: '请选择',
    options: [],
    popClassName: '',
    popStyle: '',
    maskClosable: true,
    onFormat: null,
    emptyText: '暂无数据',
};
