export var PickerDefaultProps = {
    formattedValueText: null,
    visible: null,
    defaultVisible: null,
    animationType: 'transform',
    value: null,
    defaultValue: null,
    disabled: false,
    title: '',
    okText: undefined,
    cancelText: undefined,
    placeholder: undefined,
    options: [],
    popClassName: '',
    popStyle: '',
    maskClosable: true,
    onFormat: null,
    emptyText: undefined,
};
