export var DateRangePickerDefaultProps = {
    visible: null,
    defaultVisible: null,
    animationType: 'transform',
    format: 'YYYY/MM/DD',
    min: null,
    max: null,
    value: null,
    defaultValue: null,
    title: '',
    okText: null,
    cancelText: null,
    placeholder: null,
    precision: 'day',
    splitCharacter: '-',
    startPlaceholder: null,
    endPlaceholder: null,
    maskClosable: true,
    popClassName: '',
    popStyle: '',
    disabled: false,
    onFormatLabel: null,
    onFormat: null,
};
