// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhaolin/__CODES__/_mini/ant-design-mini/.dumi/theme/builtins/Previewer/index.tsx';
