// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/houmi/Desktop/work-project/ant-design-mini/.dumi/theme/builtins/Previewer/index.tsx';
