// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhaolin/__CODES__/_mini/ant-design-mini/node_modules/dumi/theme-default/builtins/SourceCode/index.js';
