export var InputBlurDefaultProps = {
    value: null,
    defaultValue: null,
    placeholder: null,
    placeholderClassName: '',
    placeholderStyle: '',
    enableNative: null,
    confirmType: null,
    confirmHold: null,
    alwaysSystem: null,
    selectionStart: null,
    selectionEnd: null,
    cursor: null,
    controlled: null,
    inputClassName: null,
    inputStyle: null,
    focus: null,
    password: null,
    disabled: null,
    name: null,
    type: null,
    randomNumber: null,
    // 微信小程序的 maxLength 需要为 -1 才能不限制输入长度。 不能传 null
    maxLength: -1,
};
