export const API_PREFIX = "## API \n\n";
export const PROP_PREIFX = "### 属性 \n\n";
export const METHOD_PREFIX = "### 事件 \n\n";
export const CLASS_PREFIX = "### 样式类 \n\n";
export const CSS_VAR_PREFIX = "### CSS 变量 \n\n";
export const PROP_TABLE_PREFIX = `| 属性 | 类型 | 必填 | 默认值 | 说明 |\n| -----|-----|-----|-----|----- |\n`;
export const METHOD_TABLE_PREFIX = `| 事件名 | 说明 | 类型 |\n| -----|-----|----- |\n`;
export const CLASS_TABLE_PREFIX = `| 类名 | 说明 |\n| -----|----- |\n`;
export const CSS_VAR_TABLE_PREFIX = `| CSS 变量名称 | 说明 |\n| -----|----- |\n`;
