export var ModalDefaultProps = {
    visible: false,
    maskClosable: true,
    closable: true,
    type: 'default',
    duration: 200,
    animation: true,
    zIndex: 998,
};
export var ModalFunctionalProps = {
    bodyClassName: '',
    bodyStyle: '',
    maskClassName: '',
    maskStyle: '',
    maskClosable: true,
    type: 'default',
    closable: true,
    duration: 200,
    animation: true,
    zIndex: 998,
    title: '',
    content: '',
    visible: false,
    destroyOnClose: false,
    primaryButtonText: '',
    secondaryButtonText: '',
    cancelButtonText: '',
    primaryButtonStyle: '',
    secondaryButtonStyle: '',
    cancelButtonStyle: '',
};
